{
    'name': 'Pet Clinic Management',
    'version': '1.0',
    'category': 'Services',
    'summary': 'Manage pet clinic appointments, vaccinations, and treatments.',
    'sequence': 1,
    'author': 'Alan Technologies LLP',
    'website': "https://alantechnologies.in/",
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/pet_views.xml',
        'views/appointment_views.xml',
        'views/vaccination_views.xml',
        'views/treatment_views.xml',
        'views/prescription_views.xml',
        'views/vaccine_views.xml',
        'views/medicine_views.xml',
    ],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'AGPL-3',
}
