{
    'name': "Hotel Management",
    'version': "18.0.1.0",
    'license': "LGPL-3",
    'summary': """Manages Room bookings""",
    'description': """Hotel management handles bookings, check-ins, billing, and services to ensure smooth hotel operations""",
    'author': "Alan Technologies",
    'category': "Management",
    'sequence': 1,
    'depends': ['base', 'mail', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/booking_sequence.xml',
        'report/hotel_booking_report_template.xml',
        'report/hotel_booking_report.xml',
        'views/hotel_views.xml',
        'views/hotel_report_views.xml',
        'views/hotel_report_menus.xml',
    ],
    'images': ['static/description/banner.gif'],
    'application': True,
    'auto_install': False,
    'installation': True,
}