{
    'name': "School Management",
    'summary': "School Management Module",
    'description': """ """,
    'author': "Alan Technologies",
    'website': "https://alantechnologies.in/",
    'category': 'Education',
    'version': '1.0',
    'depends': ['base', 'contacts', 'hr'],
    'data': [
    'security/ir.model.access.csv',
    'views/student.xml',
    'views/parent.xml',
    'views/student_document.xml',
    'views/classes.xml',
    'views/subject.xml',
    'views/teacher.xml',
    'views/exam.xml',
    'views/exam_result.xml',
    'views/transport.xml',
    'views/fee.xml',
    'views/hostel.xml',
    'views/fee_type.xml',
    ],
    'demo': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}